### PR TITLE
Return non-zero exit code on failures, add playbook not found console messages

### PR DESCRIPTION
**Pull request by davidtlascelles**
- Returns exit code 1 if any `ansible-playbook` sub-process has non-zero exit code.
- Returns exit code 1 if any playbook file is not found
- Prints helpful "Playbook not found" messages in the progression and recap

### CODE REVIEW

**Comment by davidtlascelles** [comment]
Hey @JulienPalard, would you mind taking a look at this PR soon? Thanks!

**Comment by JulienPalard** [comment]
"Sorry" for the latency, I was on holidays :D

And now I have 100+ unread github notifications :,-(

So I like the idea of your PR but I think the "playbook not found" could be raised way sooner, around argument parsing. It would make sense: I think it would be saner to not even start anything if a playbook is not found.

**Comment by davidtlascelles** [comment]
Yeah, that's a good idea. The latest changes should fail immediately if the playbook args don't point to a file.

I also added support for any `ERROR` lines in the output from ansible, e.g. when your `/file/path/glob/*` includes some .txt files accidentally and Ansible complains: `ERROR! Empty playbook, nothing to do: /file/path/glob/example.txt`.

This should fix when the return code is non-zero for a process, but the error is hidden from the recap.

**Comment by JulienPalard** [comment]
o/

I tested your branch, and added two commits see here:

https://github.com/meltygroup/ansible-parallel/tree/david

The first one avoid the use of a global, and make `ansible-parallel` actually exit with the code.

The 2nd one is because I find the 'Done.' too pretty for a failed process so I tried displaying something more eye-catching. And I had to modify the 'ERROR' condition because I use PYTHONDEVMODE which place another warning at `lines[-1]`, so it was missing the error.

What do you think? Feel free to merge them in your branch if you think they're worth it.

**Comment by davidtlascelles** [comment]
Those changes look good!

**Comment by JulienPalard** [comment]
Merged it (manually as there was a small missplaced space I added a small commit to fix it).

**Comment by JulienPalard** [comment]
Please test it with your playbooks to double check it behave as expected, and I'll do a release :)

**Comment by davidtlascelles** [comment]
Works like a charm! I'm able to now detect and react to failures in my configuration scripts. Thanks for the help with this improvement.

**Pull request closed without merging**
